//! `.driver` bundle packaging helpers.
//!
//! A macOS AudioServerPlugin ships as a `.driver` *bundle* — a
//! directory `coreaudiod` loads from `/Library/Audio/Plug-Ins/HAL/`.
//! The bundle's `Info.plist` is what tells `coreaudiod` the plug-in
//! exists, which executable to load, and — crucially — the CFPlugIn
//! factory UUID and factory function name to call.
//!
//! ```text
//! MyDriver.driver/
//! └── Contents/
//!     ├── Info.plist          ← generated by this module
//!     └── MacOS/
//!         └── MyDriver        ← the cdylib from `plugin_entry!`
//! ```
//!
//! This module's [`plist`] submodule generates that `Info.plist`
//! from a [`plist::BundleConfig`]. It is cross-platform string
//! generation — no FFI — so the output can be unit-tested and
//! `plutil`-linted in CI without a macOS-only build.

pub mod plist;

pub use plist::{BundleConfig, AUDIO_SERVER_PLUGIN_TYPE_UUID};
